apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app-nginx
spec:
  selector:
    matchLabels: 
      run: kubernetes-app-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: kubernetes-app-nginx
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: nginxsecret
        - name: configmap-volume
          configMap:
            name: nginxconfigmap
      containers:
        - name: kubernetes-app-nginx
          image: nginx
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: secret-volume
            - mountPath: /etc/nginx/conf.d
              name: configmap-volume
