apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app-nginx
  labels:
    run: kubernetes-app-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 443
      name: https
    - port: 80
      name: http
  selector:
    run: kubernetes-app-nginx
