apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app-react
spec:
  replicas: 2
  selector:
    matchLabels:
      run: kubernetes-app-react
  template:
    metadata:
      labels:
        run: kubernetes-app-react
    spec:
      containers:
        - name: kubernetes-app-react
          image: dvoong/react_app:latest
